#!/bin/bash
image_name="hsa-samples"

git_directoy=$(pwd -P)
name=$image_name

docker_args=$(cat <<EOF
-it --rm\
 -e USER=$user -e UID=$uid -e GID=$gid\
 -v $git_directoy:$git_directoy\
 -w $git_directoy
EOF
)

gpu_args="--device=/dev/kfd --device=/dev/dri"
$CMD docker run --name $name $docker_args $gpu_args $image_name
